Fiap06.WEB.MVC/Models/Cidade.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap06.Web.MVC.Models
{
    public class Cidade
    {
        public int CidadeId { get; set; }
        public string Nome { get; set; }
        public DateTime DataFundacao { get; set; }

        public Regiao? Regiao { get; set; }

        public bool CarroPorAplicativo { get; set; }

        public Estado Estado { get; set; }
        public int EstadoId { get; set; }
    }
}

Fiap06.WEB.MVC/Models/Estado.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap06.Web.MVC.Models
{
    public class Estado
    {
        public int EstadoId { get; set; }
        public string Nome { get; set; }

        [MaxLength(2)]
        public string Sigla { get; set; }

        public int Populacao { get; set; }

        public List<Cidade> Cidades { get; set; }
    }
}

Fiap06.WEB.MVC/Models/Regiao.cs
namespace Fiap06.Web.MVC.Models
{
    public enum Regiao
    {
        Norte, Sul, Leste, Oeste, Nordeste, Sudeste, Sudoeste
    }
}

Fiap06.WEB.MVC/Controllers/CidadeController.cs
using Fiap06.Web.MVC.Models;
using Fiap06.Web.MVC.Persistencia;
using Fiap06.Web.MVC.UnitsOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap06.Web.MVC.Controllers
{
    public class CidadeController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpPost]
        public ActionResult Excluir(int codigo)
        {
            _unit.CidadeRepository.Excluir(codigo);
            _unit.Salvar();
            TempData["msg"] = "Cidade removida";
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Editar(Cidade cidade)
        {
            _unit.CidadeRepository.Editar(cidade);
            _unit.Salvar();
            TempData["msg"] = "Cidade atualizada";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            CarregarCombo();
            var cidade = _unit.CidadeRepository.BuscarPorCodigo(id);
            return View(cidade);
        }

        [HttpGet]
        public ActionResult Buscar(int? estado)
        {
            CarregarCombo();
            var lista = _unit.CidadeRepository
                .BuscarPor(c => c.EstadoId == estado || estado == null);
            return View("Listar",lista);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            CarregarCombo();
            var lista = _unit.CidadeRepository.Listar();
            return View(lista);
        }

        private void CarregarCombo()
        {
            var ufs = _unit.EstadoRepository.Listar();
            ViewBag.estados = new SelectList(ufs, "EstadoId", "Nome");
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            CarregarCombo();
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Cidade cidade)
        {
            _unit.CidadeRepository.Cadastrar(cidade);
            _unit.Salvar();
            TempData["msg"] = "Cidade cadastrada";
            return RedirectToAction("Cadastrar");
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

Fiap06.WEB.MVC/Controllers/EstadoController.cs
using Fiap06.Web.MVC.Models;
using Fiap06.Web.MVC.Persistencia;
using Fiap06.Web.MVC.UnitsOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap06.Web.MVC.Controllers
{
    public class EstadoController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Estado estado)
        {
            _unit.EstadoRepository.Cadastrar(estado);
            _unit.Salvar();
            TempData["msg"] = "Estado cadastrado!";
            return RedirectToAction("Cadastrar");
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

Fiap06.WEB.MVC/Views/Cidade/Cadastrar.cshtml
@model Fiap06.Web.MVC.Models.Cidade

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Cidade</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">@TempData["msg"]</div>
}

@using (@Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(c => c.Nome)
        @Html.TextBoxFor(c => c.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.DataFundacao)
        @Html.TextBoxFor(c => c.DataFundacao, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Estado)
        @Html.DropDownListFor(c => c.EstadoId,
            ViewBag.estados as SelectList,
            "Selecione", new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.Regiao)
        @Html.EnumDropDownListFor(c => c.Regiao,
            "Selecione", new { @class = "form-control" })
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
}

Fiap06.WEB.MVC/Views/Cidade/Editar.cshtml
@model Fiap06.Web.MVC.Models.Cidade

@{
    ViewBag.Title = "Editar";
}

<h2>Atualização de Cidade</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(c => c.CidadeId)
    <div class="form-group">
        @Html.LabelFor(c => c.Nome)
        @Html.TextBoxFor(c => c.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.DataFundacao)
        @Html.TextBoxFor(c => c.DataFundacao, "{0:dd/MM/yyyy}",
            new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.EstadoId)
        @Html.DropDownListFor(c => c.EstadoId, ViewBag.estados as SelectList,
            new { @class = "form-control"})
    </div>
    <input type="submit" value="Atualizar" class="btn btn-primary" />
}

Fiap06.WEB.MVC/Views/Cidade/Listar.cshtml
@model List<Fiap06.Web.MVC.Models.Cidade>

@{
    ViewBag.Title = "Listar";
}

<h2>Cidades</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm("Buscar", "Cidade",
        FormMethod.Get, new { @class = "form-inline" }))
{
    @Html.DropDownList("estado",
        ViewBag.estados as SelectList,
        "Selecione",
        new { @class = "form-control" })
    <input type="submit" value="Buscar" class="btn btn-primary" />
}
<br />
<table class="table">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Data Fundação</th>
        <th>Estado</th>
        <th>Região</th>
        <th>Carro por Aplicativo</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CidadeId</td>
            <td>@item.Nome</td>
            <td>@item.DataFundacao.ToShortDateString()</td>
            <td>@item.Estado.Sigla</td>
            <td>@item.Regiao</td>
            <td>@(item.CarroPorAplicativo?"Sim":"Não")</td>
            <td>
                <!-- Button trigger modal -->
                <button onclick="codigoCidade.value = @item.CidadeId" type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#myModal">
                    Carro por aplicativo
                </button>
                @Html.ActionLink("Editar","Editar",
                    new { id = item.CidadeId}, new { @class = "btn btn-info btn-sm"})
                <!-- Button trigger modal -->
                <button onclick="codigoCidade.value = @item.CidadeId" type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal">
                    Excluir
                </button>
            </td>
        </tr>
    }
</table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
            </div>
            <div class="modal-body">
                Deseja realmente excluir a cidade?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Excluir","Cidade"))
                {
                    <input type="hidden" name="codigo" id="codigoCidade" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-danger">Excluir</button>
                }
            </div>
        </div>
    </div>
</div>

Fiap06.WEB.MVC/Views/Estado/Cadastrar.cshtml
@model Fiap06.Web.MVC.Models.Estado

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastro de Estado</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(e => e.Nome)
        @Html.TextBoxFor(e => e.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(e => e.Sigla)
        @Html.TextBoxFor(e => e.Sigla, new { @class = "form-control"})
    </div>
    <div class="form-group">
        @Html.LabelFor(e => e.Populacao)
        @Html.TextBoxFor(e => e.Populacao, new { @class = "form-control"})
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
}

Fiap06.WEB.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Brasil", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Estado <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro","Cadastrar","Estado")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cidade <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastro","Cadastrar","Cidade")</li>
                            <li>@Html.ActionLink("Cidades","Listar","Cidade")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>